repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest --exitfirst --maxfail=1 -q
        language: system
        pass_filenames: false

  # Format, lint, and sort imports with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        name: ruff (lint code)
        args: [--fix]
      - id: ruff-format
        name: ruff (format code)

  # Type check with mypy using local configuration
  - repo: local
    hooks:
      - id: mypy
        name: mypy (type checking)
        entry: python -m mypy
        language: system
        types: [python]
        pass_filenames: false
        args:
          - --config-file=pyproject.toml
          - --package=intern_trading_game

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        pass_filenames: false        # <- ignore git-passed filenames
        # -r src/ means only scan our source code directory
        # --skip B101 tells Bandit to ignore warnings about `assert` usage
        args:
          - -r
          - src/
          - --skip
          - B101

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict  # prevents committing leftover conflict markers
      - id: end-of-file-fixer  # ensures files end with a newline
      - id: trailing-whitespace  # strips any trailing spaces

  # Custom hook to check for reStructuredText math directives
  - repo: local
    hooks:
      - id: check-math-directives
        name: Check for reStructuredText math directives
        description: Ensures math formulas use MathJax syntax instead of reST directives
        entry: .pre-commit-hooks/check_math_directives.py
        language: python
        types: [python]
