site_name: Intern Trading Game
site_description: Core simulation engine, matching logic, and reference tools for a role-based, options market-making game
repo_url: https://github.com/yourusername/Intern-Trading-Game
repo_name: Intern-Trading-Game

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.share
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  # MathJax configuration for rendering mathematical formulas
  # Use $$...$$  for display math and \(...\) for inline math in Markdown and docstrings
  # See docs/contributing/docstring-math-guide.md for usage guidelines
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

plugins:
  - search
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_source: true
            merge_init_into_class: true
            heading_level: 3
            show_category_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            separate_signature: true
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py

nav:
  - Home: index.md
  - Tutorials:
      - Market Maker Tutorial: tutorials/market-maker-tutorial.md
  - How-To Guides:
      - How to Submit Orders: how-to/how-to-submit-orders.md
  - Reference:
      - Exchange API: reference/exchange-api.md
      - Math Examples: reference/math-examples.md
      - API Reference:
          - Order Book: reference/order_book.md
          - Order: reference/order.md
          - Trade: reference/trade.md
          - Venue: reference/venue.md
          - Instrument: reference/instrument.md
  - Explanation:
      - Explaining Order Matching: explanation/explaining-order-matching.md
  - Contributing:
      - Math in Docstrings: contributing/docstring-math-guide.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
