# Default configuration for Intern Trading Game
# This file contains the baseline configuration that can be overridden

exchange:
  phase_check_interval: 0.1  # Seconds between phase transition checks (100ms)
  order_queue_timeout: 0.01  # Seconds to wait for orders before checking phases (10ms)

# Market phase configuration
market_phases:
  # Timezone for all phase times
  timezone: "America/Chicago"

  # Phase schedule (24-hour format)
  schedule:
    pre_open:
      start_time: "08:00"
      end_time: "09:29:30"
      weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

    opening_auction:
      start_time: "09:29:30"
      end_time: "09:30:00"
      weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

    continuous:
      start_time: "09:30:00"
      end_time: "16:00:00"
      weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

    # Closed is implicit - any time not covered above

  # Phase configurations
  phase_states:
    closed:
      is_order_submission_allowed: false
      is_order_cancellation_allowed: false
      is_matching_enabled: false
      execution_style: "none"

    pre_open:
      is_order_submission_allowed: true
      is_order_cancellation_allowed: true
      is_matching_enabled: false
      execution_style: "none"

    opening_auction:
      is_order_submission_allowed: false
      is_order_cancellation_allowed: false
      is_matching_enabled: true
      execution_style: "batch"

    continuous:
      is_order_submission_allowed: true
      is_order_cancellation_allowed: true
      is_matching_enabled: true
      execution_style: "continuous"

# Order response coordination configuration
response_coordinator:
  # Maximum time (seconds) to wait for order processing
  default_timeout_seconds: 5.0

  # Maximum number of concurrent pending requests
  max_pending_requests: 1000

  # How often (seconds) to clean up completed/expired requests
  cleanup_interval_seconds: 30

  # Whether to collect detailed metrics
  enable_metrics: true

  # Whether to enable detailed logging (can be verbose)
  enable_detailed_logging: false

  # Prefix for request ID generation
  request_id_prefix: "req"

roles:
  market_maker:
    fees:
      maker_rebate: 0.02   # +$0.02 per contract rebate
      taker_fee: -0.01     # -$0.01 per contract fee
    constraints:
      - type: position_limit
        parameters:
          max_position: 50
          symmetric: true
        error_code: MM_POS_LIMIT
        error_message: "Position exceeds ±50"
      - type: instrument_allowed
        parameters:
          allowed_instruments:
            - SPX_4500_CALL
            - SPX_4500_PUT
        error_code: INVALID_INSTRUMENT
        error_message: "Instrument not found"

instruments:
  - symbol: SPX_4500_CALL
    strike: 4500.0
    option_type: call
    underlying: SPX
  - symbol: SPX_4500_PUT
    strike: 4500.0
    option_type: put
    underlying: SPX
