"""Market news events affecting prices or volatility.

This module defines the NewsEvent data structure for significant
market events that may impact trading.
"""

from dataclasses import dataclass
from datetime import datetime


@dataclass
class NewsEvent:
    """Market news event affecting prices or volatility.

    Represents significant market events generated by the Event
    System via Poisson process. Events may move prices, change
    volatility regimes, or be false signals.

    Parameters
    ----------
    event_id : str
        Unique identifier for this event
    event_type : str
        Category: "regime_shift", "price_jump", "false_signal"
    description : str
        Human-readable event description
    impact_magnitude : float
        Size of potential market impact
    timestamp_announced : datetime
        When event becomes public

    Notes
    -----
    Event generation follows Poisson process with configurable
    rate (typically λ=1 per 1-4 hours). Event type probabilities
    are configurable in game parameters.

    TradingContext
    --------------
    Market Assumptions
        - News reflects real market conditions
        - Impact varies with current volatility
        - Market digests news over time

    Trading Rules
        - All players see news simultaneously
        - Some roles get advance warning via signals
        - News may or may not move markets

    Examples
    --------
    >>> event = NewsEvent(
    ...     event_id="NEWS-001",
    ...     event_type="regime_shift",
    ...     description="Fed announces rate decision",
    ...     impact_magnitude=0.02,
    ...     timestamp_announced=datetime(2024, 3, 21, 14, 0, 0)
    ... )
    >>> print(f"Breaking: {event.description}")
    Breaking: Fed announces rate decision
    """

    event_id: str
    event_type: str
    description: str
    impact_magnitude: float
    timestamp_announced: datetime
