name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package with dev dependencies
        pip install -e ".[dev]"
        # Install additional CI-only tools
        pip install coverage vulture

    - name: Run pre-commit checks
      run: pre-commit run --all-files

    - name: Run tests with coverage
      run: |
        # Run tests with coverage using the same pytest settings from pre-commit
        coverage run -m pytest --exitfirst --maxfail=1
        # Generate coverage report and fail if below 90%
        coverage report --fail-under=90

    - name: Check for dead code
      run: |
        # Check for dead code in src directory with reasonable confidence
        vulture src/intern_trading_game --min-confidence 80

    - name: Security scan with bandit
      run: |
        # Run bandit with same settings as pre-commit
        bandit -r src/ --skip B101
